version: '3.8'
services:
  frr:
    image: router_mdelwaul
    build:
      context: FRR
    container_name: router_mdelwaul
    privileged: true
    networks:
      - network_bridge
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "26010:2601"
      - "179:179"
      - "2604:2604"
    volumes:
      - ./FRR:/etc/frr
    entrypoint: ["/bin/bash", "-c", "cp /etc/frr/daemons.custom /etc/frr/daemons && /usr/lib/frr/frrinit.sh start"]


  alpine:
    image: host_mdelwaul
    build:
      context: Alpine
    container_name : host_mdelwaul
    networks:
      - network_bridge
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  network_bridge:
    driver: bridge
    
