version: '3.8'
services:
  frr:
    image: router_mdelwaul
    build:
      context: FRR
    container_name: router_mdelwaul
    privileged: true
    networks:
      - network_bridge
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    stdin_open: true
    tty: true
    #entrypoint: ["/bin/bash", "-c", "/usr/lib/frr/frrinit.sh start && tail -f /dev/null"]  # Overrides the entrypoint and allows volume mounting
    ports:
      - "26010:2601"
      - "179:179"
      - "2604:2604"
    volumes:
      - ./FRR:/etc/frr
      - ./Test:/etc


  alpine:
    image: host_mdelwaul
    build:
      context: Alpine
    container_name : host_mdelwaul
    networks:
      - network_bridge
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  network_bridge:
    driver: bridge
    
