version: '3.8'

services:
  frr:
    image: router_mdelwaul
    build:
      context: FRR
    container_name: router_mdelwaul
    privileged: true
    network_mode: "none"  # Let GNS3 control interfaces
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    stdin_open: true
    tty: true

  alpine:
    image: host_mdelwaul
    build:
      context: Alpine
    container_name: host_mdelwaul
    privileged: true
    network_mode: "none"  # Let GNS3 control interfaces
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    stdin_open: true
    tty: true

